//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.UserAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsToObjects
    {
        public long ID { get; set; }
        public string Form { get; set; }
        public Nullable<long> ObjectsID { get; set; }
    
        public virtual AccessObject AccessObject { get; set; }
    }
}
