//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.UserAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xaccessEntities : DbContext
    {
        public xaccessEntities()
            : base("name=xaccessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activity { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<AccessCategory> AccessCategory { get; set; }
        public virtual DbSet<AccessLevel> AccessLevel { get; set; }
        public virtual DbSet<AccessObject> AccessObject { get; set; }
        public virtual DbSet<FormsToObjects> FormsToObjects { get; set; }
        public virtual DbSet<UsersAccessLevelToObjects> UsersAccessLevelToObjects { get; set; }
    }
}
