//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeBaseRW3_2015
    {
        public long ID { get; set; }
        public short Year { get; set; }
        public decimal Tar21 { get; set; }
        public decimal Tar22 { get; set; }
    }
}
