//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DopTariff
    {
        public long ID { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<decimal> Tariff1 { get; set; }
        public Nullable<decimal> Tariff2 { get; set; }
    }
}
