//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_M_2016_Staff
    {
        public long ID { get; set; }
        public long FormsSZV_M_2016_ID { get; set; }
        public long StaffID { get; set; }
    
        public virtual FormsSZV_M_2016 FormsSZV_M_2016 { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
