//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsDSW_3_Staff
    {
        public long ID { get; set; }
        public long FormsDSW_3_ID { get; set; }
        public long StaffID { get; set; }
        public Nullable<decimal> SUMFEEPFR_EMPLOYERS { get; set; }
        public Nullable<decimal> SUMFEEPFR_PAYER { get; set; }
    
        public virtual FormsDSW_3 FormsDSW_3 { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
