//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRSW
    {
        public long ID { get; set; }
        public long StaffID { get; set; }
        public Nullable<System.DateTime> DateBeginEnquiry { get; set; }
        public Nullable<System.DateTime> DateEndEnquiry { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
