//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_M_2016
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormsSZV_M_2016()
        {
            this.FormsSZV_M_2016_Staff = new HashSet<FormsSZV_M_2016_Staff>();
        }
    
        public long ID { get; set; }
        public short YEAR { get; set; }
        public byte MONTH { get; set; }
        public long InsurerID { get; set; }
        public long TypeInfoID { get; set; }
        public System.DateTime DateFilling { get; set; }
    
        public virtual TypeInfo TypeInfo { get; set; }
        public virtual Insurer Insurer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_M_2016_Staff> FormsSZV_M_2016_Staff { get; set; }
    }
}
