//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRSW2014_1_Razd_5
    {
        public long ID { get; set; }
        public short Year { get; set; }
        public byte Quarter { get; set; }
        public Nullable<long> InsurerID { get; set; }
        public Nullable<byte> CorrectionNum { get; set; }
        public Nullable<long> NumOrd { get; set; }
        public string Insurance { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string NumSpravka { get; set; }
        public Nullable<System.DateTime> DateSpravka { get; set; }
        public string NumSpravka1 { get; set; }
        public Nullable<System.DateTime> DateSpravka1 { get; set; }
        public Nullable<decimal> SumPay { get; set; }
        public Nullable<decimal> SumPay_0 { get; set; }
        public Nullable<decimal> SumPay_1 { get; set; }
        public Nullable<decimal> SumPay_2 { get; set; }
    }
}
