//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsADW_2
    {
        public long ID { get; set; }
        public Nullable<short> Type_DateBirth { get; set; }
        public Nullable<short> DateBirthDay_Os { get; set; }
        public Nullable<short> DateBirthMonth_Os { get; set; }
        public Nullable<short> DateBirthYear_Os { get; set; }
        public Nullable<short> Type_PlaceBirth { get; set; }
        public string Punkt { get; set; }
        public string Distr { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string Citizenship { get; set; }
        public Nullable<long> Doc_Type_ID { get; set; }
        public string Doc_Name { get; set; }
        public string Ser_Lat { get; set; }
        public string Ser_Rus { get; set; }
        public string Doc_Num { get; set; }
        public Nullable<System.DateTime> Doc_Date { get; set; }
        public string Doc_Kem_Vyd { get; set; }
        public string Reg_Addr { get; set; }
        public string Fakt_Addr { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DateFilling { get; set; }
        public Nullable<short> DispatchPFR { get; set; }
        public Nullable<long> UserInfo { get; set; }
        public Nullable<long> UserUnloadInfo { get; set; }
        public Nullable<long> StaffID { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public Nullable<short> Num { get; set; }
        public string PlaceBirthCancel { get; set; }
        public string MiddleNameCancel { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<byte> Sex { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
