//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_KORR_4_2017
    {
        public long ID { get; set; }
        public long FormsSZV_KORR_2017_ID { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<decimal> SumFeePFR { get; set; }
        public Nullable<decimal> BaseALL { get; set; }
        public Nullable<decimal> BaseGPD { get; set; }
        public Nullable<decimal> SumPrevBaseALL { get; set; }
        public Nullable<decimal> SumPrevBaseGPD { get; set; }
        public Nullable<decimal> SumFeeBefore2001Insurer { get; set; }
        public Nullable<decimal> SumFeeBefore2001Staff { get; set; }
        public Nullable<decimal> SumFeeAfter2001STRAH { get; set; }
        public Nullable<decimal> SumFeeAfter2001NAKOP { get; set; }
        public Nullable<decimal> SumPaySTRAH { get; set; }
        public Nullable<decimal> SumPayNAKOP { get; set; }
        public Nullable<decimal> SumFeeTarSV { get; set; }
    
        public virtual FormsSZV_KORR_2017 FormsSZV_KORR_2017 { get; set; }
    }
}
