//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRSW2014_1_Razd_4
    {
        public long ID { get; set; }
        public short Year { get; set; }
        public byte Quarter { get; set; }
        public Nullable<long> InsurerID { get; set; }
        public Nullable<byte> CorrectionNum { get; set; }
        public Nullable<long> NumOrd { get; set; }
        public Nullable<byte> Base { get; set; }
        public Nullable<byte> CodeBase { get; set; }
        public Nullable<short> YearPer { get; set; }
        public Nullable<byte> MonthPer { get; set; }
        public Nullable<decimal> Strah2014 { get; set; }
        public Nullable<decimal> StrahMoreBase2014 { get; set; }
        public Nullable<decimal> Strah2013 { get; set; }
        public Nullable<decimal> StrahMoreBase2013 { get; set; }
        public Nullable<decimal> Nakop2013 { get; set; }
        public Nullable<decimal> Dop1 { get; set; }
        public Nullable<decimal> Dop2 { get; set; }
        public Nullable<decimal> Dop21 { get; set; }
        public Nullable<decimal> OMS { get; set; }
    }
}
