//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_ISH_2017
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormsSZV_ISH_2017()
        {
            this.FormsSZV_ISH_4_2017 = new HashSet<FormsSZV_ISH_4_2017>();
            this.FormsSZV_ISH_7_2017 = new HashSet<FormsSZV_ISH_7_2017>();
            this.StajOsn = new HashSet<StajOsn>();
        }
    
        public long ID { get; set; }
        public short Year { get; set; }
        public byte Code { get; set; }
        public Nullable<long> InsurerID { get; set; }
        public long StaffID { get; set; }
        public Nullable<long> FormsODV_1_2017_ID { get; set; }
        public Nullable<byte> ContractType { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public string ContractNum { get; set; }
        public string DopTarCode { get; set; }
        public System.DateTime DateFilling { get; set; }
        public Nullable<decimal> SumFeePFR_Insurer { get; set; }
        public Nullable<decimal> SumFeePFR_Staff { get; set; }
        public Nullable<decimal> SumFeePFR_Tar { get; set; }
        public Nullable<decimal> SumFeePFR_TarDop { get; set; }
        public Nullable<decimal> SumFeePFR_Strah { get; set; }
        public Nullable<decimal> SumFeePFR_Nakop { get; set; }
        public Nullable<decimal> SumFeePFR_Base { get; set; }
        public Nullable<decimal> SumPayPFR_Strah { get; set; }
        public Nullable<decimal> SumPayPFR_Nakop { get; set; }
        public Nullable<bool> Dismissed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_ISH_4_2017> FormsSZV_ISH_4_2017 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_ISH_7_2017> FormsSZV_ISH_7_2017 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StajOsn> StajOsn { get; set; }
        public virtual FormsODV_1_2017 FormsODV_1_2017 { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
