//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRSW2014_1_Razd_6_7
    {
        public long ID { get; set; }
        public Nullable<long> SpecOcenkaUslTrudaID { get; set; }
        public Nullable<decimal> s_0_0 { get; set; }
        public Nullable<decimal> s_0_1 { get; set; }
        public Nullable<decimal> s_1_0 { get; set; }
        public Nullable<decimal> s_1_1 { get; set; }
        public Nullable<decimal> s_2_0 { get; set; }
        public Nullable<decimal> s_2_1 { get; set; }
        public Nullable<decimal> s_3_0 { get; set; }
        public Nullable<decimal> s_3_1 { get; set; }
        public long FormsRSW2014_1_Razd_6_1_ID { get; set; }
    
        public virtual FormsRSW2014_1_Razd_6_1 FormsRSW2014_1_Razd_6_1 { get; set; }
        public virtual SpecOcenkaUslTruda SpecOcenkaUslTruda { get; set; }
    }
}
