//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRSW2014_1_Razd_2_5_2
    {
        public long ID { get; set; }
        public short Year { get; set; }
        public byte Quarter { get; set; }
        public Nullable<long> InsurerID { get; set; }
        public Nullable<byte> CorrectionNum { get; set; }
        public Nullable<long> NumRec { get; set; }
        public Nullable<byte> Col_2_QuarterKorr { get; set; }
        public Nullable<long> Col_3_YearKorr { get; set; }
        public Nullable<decimal> Col_4 { get; set; }
        public Nullable<decimal> Col_5 { get; set; }
        public Nullable<decimal> Col_6 { get; set; }
        public Nullable<long> Col_7 { get; set; }
        public string Col_8 { get; set; }
    }
}
