//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_TD_2020_Staff_Events
    {
        public long ID { get; set; }
        public long FormsSZV_TD_2020_Staff_ID { get; set; }
        public System.Guid UUID { get; set; }
        public long TypesOfEvents_ID { get; set; }
        public System.DateTime DateOfEvent { get; set; }
        public byte Sovmestitel { get; set; }
        public string Svedenia { get; set; }
        public string Dolgn { get; set; }
        public string Department { get; set; }
        public string Statya { get; set; }
        public string Punkt { get; set; }
        public string OsnUvolName { get; set; }
        public string OsnUvolStartya { get; set; }
        public string OsnUvolChyast { get; set; }
        public string OsnUvolPunkt { get; set; }
        public string OsnUvolPodPunkt { get; set; }
        public string Prichina { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public string OsnName1 { get; set; }
        public Nullable<System.DateTime> OsnDate1 { get; set; }
        public string OsnNum1 { get; set; }
        public string OsnSer1 { get; set; }
        public string OsnName2 { get; set; }
        public Nullable<System.DateTime> OsnDate2 { get; set; }
        public string OsnNum2 { get; set; }
        public string OsnSer2 { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<bool> Annuled { get; set; }
        public Nullable<System.DateTime> AnnuleDate { get; set; }
        public string VydPoruchRaboty { get; set; }
        public string KodVypFunc { get; set; }
    
        public virtual FormsSZV_TD_2020_Staff FormsSZV_TD_2020_Staff { get; set; }
        public virtual FormsSZV_TD_2020_TypesOfEvents FormsSZV_TD_2020_TypesOfEvents { get; set; }
    }
}
