//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsODV_1_2017
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormsODV_1_2017()
        {
            this.FormsODV_1_4_2017 = new HashSet<FormsODV_1_4_2017>();
            this.FormsODV_1_5_2017 = new HashSet<FormsODV_1_5_2017>();
            this.FormsSZV_ISH_2017 = new HashSet<FormsSZV_ISH_2017>();
            this.FormsSZV_KORR_2017 = new HashSet<FormsSZV_KORR_2017>();
            this.FormsSZV_STAJ_2017 = new HashSet<FormsSZV_STAJ_2017>();
        }
    
        public long ID { get; set; }
        public short Year { get; set; }
        public byte Code { get; set; }
        public Nullable<long> InsurerID { get; set; }
        public Nullable<byte> TypeInfo { get; set; }
        public Nullable<long> StaffCount { get; set; }
        public Nullable<decimal> s_0_0 { get; set; }
        public Nullable<decimal> s_0_1 { get; set; }
        public Nullable<decimal> s_0_2 { get; set; }
        public Nullable<decimal> s_0_3 { get; set; }
        public Nullable<decimal> s_1_0 { get; set; }
        public Nullable<decimal> s_1_1 { get; set; }
        public Nullable<decimal> s_1_2 { get; set; }
        public Nullable<decimal> s_1_3 { get; set; }
        public Nullable<decimal> s_2_0 { get; set; }
        public Nullable<decimal> s_2_1 { get; set; }
        public Nullable<decimal> s_2_2 { get; set; }
        public Nullable<decimal> s_2_3 { get; set; }
        public Nullable<decimal> StaffCountOsobUslShtat { get; set; }
        public Nullable<long> StaffCountOsobUslFakt { get; set; }
        public System.DateTime DateFilling { get; set; }
        public string ConfirmLastName { get; set; }
        public string ConfirmFirstName { get; set; }
        public string ConfirmMiddleName { get; set; }
        public string ConfirmDolgn { get; set; }
        public Nullable<bool> DispatchPFR { get; set; }
        public Nullable<byte> TypeForm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsODV_1_4_2017> FormsODV_1_4_2017 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsODV_1_5_2017> FormsODV_1_5_2017 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_ISH_2017> FormsSZV_ISH_2017 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_KORR_2017> FormsSZV_KORR_2017 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_STAJ_2017> FormsSZV_STAJ_2017 { get; set; }
    }
}
