//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsDSW_3
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormsDSW_3()
        {
            this.FormsDSW_3_Staff = new HashSet<FormsDSW_3_Staff>();
        }
    
        public long ID { get; set; }
        public Nullable<long> DepartmentID { get; set; }
        public short YEAR { get; set; }
        public string NUMBERPAYMENT { get; set; }
        public System.DateTime DATEPAYMENT { get; set; }
        public System.DateTime DATEEXECUTPAYMENT { get; set; }
        public Nullable<bool> DISPATCHPFR { get; set; }
        public long InsurerID { get; set; }
        public System.DateTime DateFilling { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Insurer Insurer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsDSW_3_Staff> FormsDSW_3_Staff { get; set; }
    }
}
