//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRSW2014_2_3
    {
        public long ID { get; set; }
        public long FormsRSW2014_2_1D { get; set; }
        public Nullable<long> NumRec { get; set; }
        public Nullable<byte> CodeBase { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<byte> ControlNumber { get; set; }
        public short Year { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<decimal> SumOPS_D { get; set; }
        public Nullable<decimal> SumStrah_D { get; set; }
        public Nullable<decimal> SumNakop_D { get; set; }
        public Nullable<decimal> SumOMS_D { get; set; }
    
        public virtual FormsRSW2014_2_1 FormsRSW2014_2_1 { get; set; }
    }
}
