//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSPW2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormsSPW2()
        {
            this.StajOsn = new HashSet<StajOsn>();
        }
    
        public long ID { get; set; }
        public short Year { get; set; }
        public byte Quarter { get; set; }
        public Nullable<long> InsurerID { get; set; }
        public long StaffID { get; set; }
        public Nullable<long> PlatCategoryID { get; set; }
        public long TypeInfoID { get; set; }
        public Nullable<short> YearKorr { get; set; }
        public Nullable<byte> QuarterKorr { get; set; }
        public System.DateTime DateComposit { get; set; }
        public System.DateTime DateFilling { get; set; }
        public Nullable<byte> ExistsInsurOPS { get; set; }
        public Nullable<byte> ExistsInsurDop { get; set; }
        public Nullable<byte> DispatchPFR { get; set; }
    
        public virtual TypeInfo TypeInfo { get; set; }
        public virtual PlatCategory PlatCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StajOsn> StajOsn { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
