//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRSW2014_1_Razd_2_1
    {
        public long ID { get; set; }
        public short Year { get; set; }
        public byte Quarter { get; set; }
        public Nullable<long> InsurerID { get; set; }
        public Nullable<byte> CorrectionNum { get; set; }
        public Nullable<long> TariffCodeID { get; set; }
        public Nullable<bool> AutoCalc { get; set; }
        public Nullable<decimal> s_200_0 { get; set; }
        public Nullable<decimal> s_200_1 { get; set; }
        public Nullable<decimal> s_200_2 { get; set; }
        public Nullable<decimal> s_200_3 { get; set; }
        public Nullable<decimal> s_201_0 { get; set; }
        public Nullable<decimal> s_201_1 { get; set; }
        public Nullable<decimal> s_201_2 { get; set; }
        public Nullable<decimal> s_201_3 { get; set; }
        public Nullable<decimal> s_202_0 { get; set; }
        public Nullable<decimal> s_202_1 { get; set; }
        public Nullable<decimal> s_202_2 { get; set; }
        public Nullable<decimal> s_202_3 { get; set; }
        public Nullable<decimal> s_203_0 { get; set; }
        public Nullable<decimal> s_203_1 { get; set; }
        public Nullable<decimal> s_203_2 { get; set; }
        public Nullable<decimal> s_203_3 { get; set; }
        public Nullable<decimal> s_204_0 { get; set; }
        public Nullable<decimal> s_204_1 { get; set; }
        public Nullable<decimal> s_204_2 { get; set; }
        public Nullable<decimal> s_204_3 { get; set; }
        public Nullable<decimal> s_205_0 { get; set; }
        public Nullable<decimal> s_205_1 { get; set; }
        public Nullable<decimal> s_205_2 { get; set; }
        public Nullable<decimal> s_205_3 { get; set; }
        public Nullable<decimal> s_206_0 { get; set; }
        public Nullable<decimal> s_206_1 { get; set; }
        public Nullable<decimal> s_206_2 { get; set; }
        public Nullable<decimal> s_206_3 { get; set; }
        public Nullable<long> s_207_0 { get; set; }
        public Nullable<long> s_207_1 { get; set; }
        public Nullable<long> s_207_2 { get; set; }
        public Nullable<long> s_207_3 { get; set; }
        public Nullable<long> s_208_0 { get; set; }
        public Nullable<long> s_208_1 { get; set; }
        public Nullable<long> s_208_2 { get; set; }
        public Nullable<long> s_208_3 { get; set; }
        public Nullable<decimal> s_210_0 { get; set; }
        public Nullable<decimal> s_210_1 { get; set; }
        public Nullable<decimal> s_210_2 { get; set; }
        public Nullable<decimal> s_210_3 { get; set; }
        public Nullable<decimal> s_211_0 { get; set; }
        public Nullable<decimal> s_211_1 { get; set; }
        public Nullable<decimal> s_211_2 { get; set; }
        public Nullable<decimal> s_211_3 { get; set; }
        public Nullable<decimal> s_212_0 { get; set; }
        public Nullable<decimal> s_212_1 { get; set; }
        public Nullable<decimal> s_212_2 { get; set; }
        public Nullable<decimal> s_212_3 { get; set; }
        public Nullable<decimal> s_213_0 { get; set; }
        public Nullable<decimal> s_213_1 { get; set; }
        public Nullable<decimal> s_213_2 { get; set; }
        public Nullable<decimal> s_213_3 { get; set; }
        public Nullable<decimal> s_214_0 { get; set; }
        public Nullable<decimal> s_214_1 { get; set; }
        public Nullable<decimal> s_214_2 { get; set; }
        public Nullable<decimal> s_214_3 { get; set; }
        public Nullable<decimal> s_215_0 { get; set; }
        public Nullable<decimal> s_215_1 { get; set; }
        public Nullable<decimal> s_215_2 { get; set; }
        public Nullable<decimal> s_215_3 { get; set; }
        public Nullable<long> s_215i_0 { get; set; }
        public Nullable<long> s_215i_1 { get; set; }
        public Nullable<long> s_215i_2 { get; set; }
        public Nullable<long> s_215i_3 { get; set; }
    
        public virtual TariffCode TariffCode { get; set; }
    }
}
