//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRW3_2015
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormsRW3_2015()
        {
            this.FormsRW3_2015_Razd_3 = new HashSet<FormsRW3_2015_Razd_3>();
        }
    
        public long ID { get; set; }
        public long InsurerID { get; set; }
        public Nullable<bool> AutoCalc { get; set; }
        public short Year { get; set; }
        public byte Quarter { get; set; }
        public byte CorrectionNum { get; set; }
        public byte WorkStop { get; set; }
        public byte CodeTar { get; set; }
        public Nullable<byte> CountConfirmDoc { get; set; }
        public byte ConfirmType { get; set; }
        public string ConfirmLastName { get; set; }
        public string ConfirmFirstName { get; set; }
        public string ConfirmMiddleName { get; set; }
        public string ConfirmOrgName { get; set; }
        public Nullable<long> ConfirmDocType_ID { get; set; }
        public string ConfirmDocName { get; set; }
        public string ConfirmDocSerLat { get; set; }
        public Nullable<long> ConfirmDocNum { get; set; }
        public Nullable<System.DateTime> ConfirmDocDate { get; set; }
        public string ConfirmDocKemVyd { get; set; }
        public Nullable<System.DateTime> ConfirmDocDateBegin { get; set; }
        public Nullable<System.DateTime> ConfirmDocDateEnd { get; set; }
        public Nullable<System.DateTime> DateUnderwrite { get; set; }
        public Nullable<decimal> s_100_0 { get; set; }
        public Nullable<decimal> s_110_0 { get; set; }
        public Nullable<decimal> s_111_0 { get; set; }
        public Nullable<decimal> s_112_0 { get; set; }
        public Nullable<decimal> s_113_0 { get; set; }
        public Nullable<decimal> s_114_0 { get; set; }
        public Nullable<decimal> s_120_0 { get; set; }
        public Nullable<decimal> s_130_0 { get; set; }
        public Nullable<decimal> s_140_0 { get; set; }
        public Nullable<decimal> s_141_0 { get; set; }
        public Nullable<decimal> s_142_0 { get; set; }
        public Nullable<decimal> s_143_0 { get; set; }
        public Nullable<decimal> s_144_0 { get; set; }
        public Nullable<decimal> s_150_0 { get; set; }
        public Nullable<decimal> s_200_0 { get; set; }
        public Nullable<decimal> s_200_1 { get; set; }
        public Nullable<decimal> s_200_2 { get; set; }
        public Nullable<decimal> s_200_3 { get; set; }
        public Nullable<decimal> s_210_0 { get; set; }
        public Nullable<decimal> s_210_1 { get; set; }
        public Nullable<decimal> s_210_2 { get; set; }
        public Nullable<decimal> s_210_3 { get; set; }
        public Nullable<decimal> s_220_0 { get; set; }
        public Nullable<decimal> s_220_1 { get; set; }
        public Nullable<decimal> s_220_2 { get; set; }
        public Nullable<decimal> s_220_3 { get; set; }
        public Nullable<long> s_230_0 { get; set; }
        public Nullable<long> s_230_1 { get; set; }
        public Nullable<long> s_230_2 { get; set; }
        public Nullable<long> s_230_3 { get; set; }
    
        public virtual Insurer Insurer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsRW3_2015_Razd_3> FormsRW3_2015_Razd_3 { get; set; }
    }
}
