//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRSW2014_1_Razd_2_4
    {
        public long ID { get; set; }
        public short Year { get; set; }
        public byte Quarter { get; set; }
        public Nullable<long> InsurerID { get; set; }
        public Nullable<byte> CorrectionNum { get; set; }
        public Nullable<byte> CodeBase { get; set; }
        public Nullable<byte> FilledBase { get; set; }
        public Nullable<bool> AutoCalc { get; set; }
        public Nullable<decimal> s_240_0 { get; set; }
        public Nullable<decimal> s_240_1 { get; set; }
        public Nullable<decimal> s_240_2 { get; set; }
        public Nullable<decimal> s_240_3 { get; set; }
        public Nullable<decimal> s_241_0 { get; set; }
        public Nullable<decimal> s_241_1 { get; set; }
        public Nullable<decimal> s_241_2 { get; set; }
        public Nullable<decimal> s_241_3 { get; set; }
        public Nullable<decimal> s_243_0 { get; set; }
        public Nullable<decimal> s_243_1 { get; set; }
        public Nullable<decimal> s_243_2 { get; set; }
        public Nullable<decimal> s_243_3 { get; set; }
        public Nullable<decimal> s_244_0 { get; set; }
        public Nullable<decimal> s_244_1 { get; set; }
        public Nullable<decimal> s_244_2 { get; set; }
        public Nullable<decimal> s_244_3 { get; set; }
        public Nullable<long> s_245_0 { get; set; }
        public Nullable<long> s_245_1 { get; set; }
        public Nullable<long> s_245_2 { get; set; }
        public Nullable<long> s_245_3 { get; set; }
        public Nullable<decimal> s_246_0 { get; set; }
        public Nullable<decimal> s_246_1 { get; set; }
        public Nullable<decimal> s_246_2 { get; set; }
        public Nullable<decimal> s_246_3 { get; set; }
        public Nullable<decimal> s_247_0 { get; set; }
        public Nullable<decimal> s_247_1 { get; set; }
        public Nullable<decimal> s_247_2 { get; set; }
        public Nullable<decimal> s_247_3 { get; set; }
        public Nullable<decimal> s_249_0 { get; set; }
        public Nullable<decimal> s_249_1 { get; set; }
        public Nullable<decimal> s_249_2 { get; set; }
        public Nullable<decimal> s_249_3 { get; set; }
        public Nullable<decimal> s_250_0 { get; set; }
        public Nullable<decimal> s_250_1 { get; set; }
        public Nullable<decimal> s_250_2 { get; set; }
        public Nullable<decimal> s_250_3 { get; set; }
        public Nullable<long> s_251_0 { get; set; }
        public Nullable<long> s_251_1 { get; set; }
        public Nullable<long> s_251_2 { get; set; }
        public Nullable<long> s_251_3 { get; set; }
        public Nullable<decimal> s_252_0 { get; set; }
        public Nullable<decimal> s_252_1 { get; set; }
        public Nullable<decimal> s_252_2 { get; set; }
        public Nullable<decimal> s_252_3 { get; set; }
        public Nullable<decimal> s_253_0 { get; set; }
        public Nullable<decimal> s_253_1 { get; set; }
        public Nullable<decimal> s_253_2 { get; set; }
        public Nullable<decimal> s_253_3 { get; set; }
        public Nullable<decimal> s_255_0 { get; set; }
        public Nullable<decimal> s_255_1 { get; set; }
        public Nullable<decimal> s_255_2 { get; set; }
        public Nullable<decimal> s_255_3 { get; set; }
        public Nullable<decimal> s_256_0 { get; set; }
        public Nullable<decimal> s_256_1 { get; set; }
        public Nullable<decimal> s_256_2 { get; set; }
        public Nullable<decimal> s_256_3 { get; set; }
        public Nullable<long> s_257_0 { get; set; }
        public Nullable<long> s_257_1 { get; set; }
        public Nullable<long> s_257_2 { get; set; }
        public Nullable<long> s_257_3 { get; set; }
        public Nullable<decimal> s_258_0 { get; set; }
        public Nullable<decimal> s_258_1 { get; set; }
        public Nullable<decimal> s_258_2 { get; set; }
        public Nullable<decimal> s_258_3 { get; set; }
        public Nullable<decimal> s_259_0 { get; set; }
        public Nullable<decimal> s_259_1 { get; set; }
        public Nullable<decimal> s_259_2 { get; set; }
        public Nullable<decimal> s_259_3 { get; set; }
        public Nullable<decimal> s_261_0 { get; set; }
        public Nullable<decimal> s_261_1 { get; set; }
        public Nullable<decimal> s_261_2 { get; set; }
        public Nullable<decimal> s_261_3 { get; set; }
        public Nullable<decimal> s_262_0 { get; set; }
        public Nullable<decimal> s_262_1 { get; set; }
        public Nullable<decimal> s_262_2 { get; set; }
        public Nullable<decimal> s_262_3 { get; set; }
        public Nullable<long> s_263_0 { get; set; }
        public Nullable<long> s_263_1 { get; set; }
        public Nullable<long> s_263_2 { get; set; }
        public Nullable<long> s_263_3 { get; set; }
        public Nullable<decimal> s_264_0 { get; set; }
        public Nullable<decimal> s_264_1 { get; set; }
        public Nullable<decimal> s_264_2 { get; set; }
        public Nullable<decimal> s_264_3 { get; set; }
        public Nullable<decimal> s_265_0 { get; set; }
        public Nullable<decimal> s_265_1 { get; set; }
        public Nullable<decimal> s_265_2 { get; set; }
        public Nullable<decimal> s_265_3 { get; set; }
        public Nullable<decimal> s_267_0 { get; set; }
        public Nullable<decimal> s_267_1 { get; set; }
        public Nullable<decimal> s_267_2 { get; set; }
        public Nullable<decimal> s_267_3 { get; set; }
        public Nullable<decimal> s_268_0 { get; set; }
        public Nullable<decimal> s_268_1 { get; set; }
        public Nullable<decimal> s_268_2 { get; set; }
        public Nullable<decimal> s_268_3 { get; set; }
        public Nullable<long> s_269_0 { get; set; }
        public Nullable<long> s_269_1 { get; set; }
        public Nullable<long> s_269_2 { get; set; }
        public Nullable<long> s_269_3 { get; set; }
    }
}
