//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_TD_2020_Staff_AnnuledEvents
    {
        public long ID { get; set; }
        public long FormsSZV_TD_2020_Staff_ID { get; set; }
        public System.Guid UUID_Annuled { get; set; }
        public Nullable<System.DateTime> Date_Annuled { get; set; }
    
        public virtual FormsSZV_TD_2020_Staff FormsSZV_TD_2020_Staff { get; set; }
    }
}
