//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRSW2014_1_Razd_3_4
    {
        public long ID { get; set; }
        public short Year { get; set; }
        public byte Quarter { get; set; }
        public Nullable<long> InsurerID { get; set; }
        public Nullable<byte> CorrectionNum { get; set; }
        public Nullable<long> NumOrd { get; set; }
        public string OKWED { get; set; }
        public string NameOKWED { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> RateIncome { get; set; }
    }
}
