//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_STAJ_4_2017
    {
        public long ID { get; set; }
        public long FormsSZV_STAJ_2017_ID { get; set; }
        public Nullable<System.DateTime> DNPO_DateFrom { get; set; }
        public Nullable<System.DateTime> DNPO_DateTo { get; set; }
        public Nullable<bool> DNPO_Fee { get; set; }
    
        public virtual FormsSZV_STAJ_2017 FormsSZV_STAJ_2017 { get; set; }
    }
}
