//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_TD_2020_Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormsSZV_TD_2020_Staff()
        {
            this.FormsSZV_TD_2020_Staff_AnnuledEvents = new HashSet<FormsSZV_TD_2020_Staff_AnnuledEvents>();
            this.FormsSZV_TD_2020_Staff_Events = new HashSet<FormsSZV_TD_2020_Staff_Events>();
        }
    
        public long ID { get; set; }
        public long FormsSZV_TD_2020_ID { get; set; }
        public long StaffID { get; set; }
        public Nullable<System.DateTime> ZayavOProdoljDate { get; set; }
        public Nullable<byte> ZayavOProdoljState { get; set; }
        public Nullable<System.DateTime> ZayavOPredostDate { get; set; }
        public Nullable<byte> ZayavOPredostState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_TD_2020_Staff_AnnuledEvents> FormsSZV_TD_2020_Staff_AnnuledEvents { get; set; }
        public virtual FormsSZV_TD_2020 FormsSZV_TD_2020 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_TD_2020_Staff_Events> FormsSZV_TD_2020_Staff_Events { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
