//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsSZV_TD_2020
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormsSZV_TD_2020()
        {
            this.FormsSZV_TD_2020_Staff = new HashSet<FormsSZV_TD_2020_Staff>();
        }
    
        public long ID { get; set; }
        public long InsurerID { get; set; }
        public short Year { get; set; }
        public byte Month { get; set; }
        public Nullable<bool> Annuled { get; set; }
        public Nullable<System.DateTime> AnnulDate { get; set; }
        public System.DateTime DateFilling { get; set; }
        public string ConfirmDolgn { get; set; }
        public string ConfirmLastName { get; set; }
        public string ConfirmFirstName { get; set; }
        public string ConfirmMiddleName { get; set; }
    
        public virtual Insurer Insurer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_TD_2020_Staff> FormsSZV_TD_2020_Staff { get; set; }
    }
}
