//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsODV_1_5_2017_OUT
    {
        public long ID { get; set; }
        public string OsobUslTrudaCode { get; set; }
        public string CodePosition { get; set; }
        public long FormsODV_1_5_2017_ID { get; set; }
    
        public virtual FormsODV_1_5_2017 FormsODV_1_5_2017 { get; set; }
    }
}
