//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormsRSW2014_2_1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormsRSW2014_2_1()
        {
            this.FormsRSW2014_2_2 = new HashSet<FormsRSW2014_2_2>();
            this.FormsRSW2014_2_3 = new HashSet<FormsRSW2014_2_3>();
        }
    
        public long ID { get; set; }
        public long InsurerID { get; set; }
        public Nullable<bool> AutoCalc { get; set; }
        public short Year { get; set; }
        public byte CorrectionNum { get; set; }
        public byte WorkStop { get; set; }
        public Nullable<long> CountEmployers { get; set; }
        public Nullable<byte> CountConfirmDoc { get; set; }
        public byte ConfirmType { get; set; }
        public string ConfirmLastName { get; set; }
        public string ConfirmFirstName { get; set; }
        public string ConfirmMiddleName { get; set; }
        public string ConfirmOrgName { get; set; }
        public Nullable<long> ConfirmDocType_ID { get; set; }
        public string ConfirmDocName { get; set; }
        public string ConfirmDocSerLat { get; set; }
        public Nullable<long> ConfirmDocNum { get; set; }
        public Nullable<System.DateTime> ConfirmDocDate { get; set; }
        public string ConfirmDocKemVyd { get; set; }
        public Nullable<System.DateTime> ConfirmDocDateBegin { get; set; }
        public Nullable<System.DateTime> ConfirmDocDateEnd { get; set; }
        public Nullable<System.DateTime> DateUnderwrite { get; set; }
        public Nullable<decimal> s_100_0 { get; set; }
        public Nullable<decimal> s_100_1 { get; set; }
        public Nullable<decimal> s_100_2 { get; set; }
        public Nullable<decimal> s_100_3 { get; set; }
        public Nullable<decimal> s_110_0 { get; set; }
        public Nullable<decimal> s_110_1 { get; set; }
        public Nullable<decimal> s_110_2 { get; set; }
        public Nullable<decimal> s_110_3 { get; set; }
        public Nullable<decimal> s_120_0 { get; set; }
        public Nullable<decimal> s_120_1 { get; set; }
        public Nullable<decimal> s_120_2 { get; set; }
        public Nullable<decimal> s_120_3 { get; set; }
        public Nullable<decimal> s_130_0 { get; set; }
        public Nullable<decimal> s_130_1 { get; set; }
        public Nullable<decimal> s_130_2 { get; set; }
        public Nullable<decimal> s_130_3 { get; set; }
        public Nullable<decimal> s_140_0 { get; set; }
        public Nullable<decimal> s_140_1 { get; set; }
        public Nullable<decimal> s_140_2 { get; set; }
        public Nullable<decimal> s_140_3 { get; set; }
        public Nullable<decimal> s_150_0 { get; set; }
        public Nullable<decimal> s_150_1 { get; set; }
        public Nullable<decimal> s_150_2 { get; set; }
        public Nullable<decimal> s_150_3 { get; set; }
    
        public virtual Insurer Insurer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsRSW2014_2_2> FormsRSW2014_2_2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsRSW2014_2_3> FormsRSW2014_2_3 { get; set; }
    }
}
