//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pu6Entities : DbContext
    {
        public pu6Entities()
            : base("name=pu6Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackupDB_Info> BackupDB_Info { get; set; }
        public virtual DbSet<CodeBaseRW3_2015> CodeBaseRW3_2015 { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DocumentTypes> DocumentTypes { get; set; }
        public virtual DbSet<Dolgn> Dolgn { get; set; }
        public virtual DbSet<DopTariff> DopTariff { get; set; }
        public virtual DbSet<FormsADW_1> FormsADW_1 { get; set; }
        public virtual DbSet<FormsADW_2> FormsADW_2 { get; set; }
        public virtual DbSet<FormsADW_3> FormsADW_3 { get; set; }
        public virtual DbSet<FormsDSW_3> FormsDSW_3 { get; set; }
        public virtual DbSet<FormsDSW_3_Staff> FormsDSW_3_Staff { get; set; }
        public virtual DbSet<FormsODV_1_4_2017> FormsODV_1_4_2017 { get; set; }
        public virtual DbSet<FormsRSW> FormsRSW { get; set; }
        public virtual DbSet<FormsRSW2014_1_1> FormsRSW2014_1_1 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_2_1> FormsRSW2014_1_Razd_2_1 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_2_4> FormsRSW2014_1_Razd_2_4 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_2_5_1> FormsRSW2014_1_Razd_2_5_1 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_2_5_2> FormsRSW2014_1_Razd_2_5_2 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_3_4> FormsRSW2014_1_Razd_3_4 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_4> FormsRSW2014_1_Razd_4 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_5> FormsRSW2014_1_Razd_5 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_6_1> FormsRSW2014_1_Razd_6_1 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_6_4> FormsRSW2014_1_Razd_6_4 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_6_6> FormsRSW2014_1_Razd_6_6 { get; set; }
        public virtual DbSet<FormsRSW2014_1_Razd_6_7> FormsRSW2014_1_Razd_6_7 { get; set; }
        public virtual DbSet<FormsRSW2014_2_1> FormsRSW2014_2_1 { get; set; }
        public virtual DbSet<FormsRSW2014_2_2> FormsRSW2014_2_2 { get; set; }
        public virtual DbSet<FormsRSW2014_2_3> FormsRSW2014_2_3 { get; set; }
        public virtual DbSet<FormsRW3_2015> FormsRW3_2015 { get; set; }
        public virtual DbSet<FormsRW3_2015_Razd_3> FormsRW3_2015_Razd_3 { get; set; }
        public virtual DbSet<FormsSPW2> FormsSPW2 { get; set; }
        public virtual DbSet<FormsSZV_6> FormsSZV_6 { get; set; }
        public virtual DbSet<FormsSZV_6_4> FormsSZV_6_4 { get; set; }
        public virtual DbSet<FormsSZV_ISH_4_2017> FormsSZV_ISH_4_2017 { get; set; }
        public virtual DbSet<FormsSZV_ISH_7_2017> FormsSZV_ISH_7_2017 { get; set; }
        public virtual DbSet<FormsSZV_KORR_4_2017> FormsSZV_KORR_4_2017 { get; set; }
        public virtual DbSet<FormsSZV_KORR_5_2017> FormsSZV_KORR_5_2017 { get; set; }
        public virtual DbSet<FormsSZV_M_2016> FormsSZV_M_2016 { get; set; }
        public virtual DbSet<FormsSZV_M_2016_Staff> FormsSZV_M_2016_Staff { get; set; }
        public virtual DbSet<FormsSZV_STAJ_4_2017> FormsSZV_STAJ_4_2017 { get; set; }
        public virtual DbSet<Insurer> Insurer { get; set; }
        public virtual DbSet<IschislStrahStajDop> IschislStrahStajDop { get; set; }
        public virtual DbSet<IschislStrahStajOsn> IschislStrahStajOsn { get; set; }
        public virtual DbSet<KodVred_1> KodVred_1 { get; set; }
        public virtual DbSet<KodVred_2> KodVred_2 { get; set; }
        public virtual DbSet<KodVred_3> KodVred_3 { get; set; }
        public virtual DbSet<MROT> MROT { get; set; }
        public virtual DbSet<OsobUslTruda> OsobUslTruda { get; set; }
        public virtual DbSet<PlatCategory> PlatCategory { get; set; }
        public virtual DbSet<PlatCategoryRaschPer> PlatCategoryRaschPer { get; set; }
        public virtual DbSet<RaschetPeriod> RaschetPeriod { get; set; }
        public virtual DbSet<SpecOcenkaUslTruda> SpecOcenkaUslTruda { get; set; }
        public virtual DbSet<SpecOcenkaUslTrudaDopTariff> SpecOcenkaUslTrudaDopTariff { get; set; }
        public virtual DbSet<StaffDateWork> StaffDateWork { get; set; }
        public virtual DbSet<StaffInfo> StaffInfo { get; set; }
        public virtual DbSet<StajLgot> StajLgot { get; set; }
        public virtual DbSet<TariffCode> TariffCode { get; set; }
        public virtual DbSet<TariffCodePlatCat> TariffCodePlatCat { get; set; }
        public virtual DbSet<TariffPlat> TariffPlat { get; set; }
        public virtual DbSet<TerrUsl> TerrUsl { get; set; }
        public virtual DbSet<TypeInfo> TypeInfo { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersActivity> UsersActivity { get; set; }
        public virtual DbSet<UslDosrNazn> UslDosrNazn { get; set; }
        public virtual DbSet<UslDosrNaznEdIzm> UslDosrNaznEdIzm { get; set; }
        public virtual DbSet<VidTrudDeyat> VidTrudDeyat { get; set; }
        public virtual DbSet<ZAGS_Born> ZAGS_Born { get; set; }
        public virtual DbSet<ZAGS_Death> ZAGS_Death { get; set; }
        public virtual DbSet<FormsSZV_STAJ_2017> FormsSZV_STAJ_2017 { get; set; }
        public virtual DbSet<StajOsn> StajOsn { get; set; }
        public virtual DbSet<FormsODV_1_5_2017_OUT> FormsODV_1_5_2017_OUT { get; set; }
        public virtual DbSet<FormsSZV_KORR_2017> FormsSZV_KORR_2017 { get; set; }
        public virtual DbSet<FormsSZV_ISH_2017> FormsSZV_ISH_2017 { get; set; }
        public virtual DbSet<FormsPredPens_Zapros> FormsPredPens_Zapros { get; set; }
        public virtual DbSet<FormsPredPens_Zapros_Staff> FormsPredPens_Zapros_Staff { get; set; }
        public virtual DbSet<FormsODV_1_5_2017> FormsODV_1_5_2017 { get; set; }
        public virtual DbSet<FormsODV_1_2017> FormsODV_1_2017 { get; set; }
        public virtual DbSet<FormsSZV_TD_2020_Staff> FormsSZV_TD_2020_Staff { get; set; }
        public virtual DbSet<FormsSZV_TD_2020_TypesOfEvents> FormsSZV_TD_2020_TypesOfEvents { get; set; }
        public virtual DbSet<FormsSZV_TD_2020_Staff_AnnuledEvents> FormsSZV_TD_2020_Staff_AnnuledEvents { get; set; }
        public virtual DbSet<FormsSZV_TD_2020> FormsSZV_TD_2020 { get; set; }
        public virtual DbSet<FormsSZV_TD_2020_Staff_Events> FormsSZV_TD_2020_Staff_Events { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
    }
}
