//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlatCategory()
        {
            this.FormsRSW2014_1_Razd_6_4 = new HashSet<FormsRSW2014_1_Razd_6_4>();
            this.FormsSPW2 = new HashSet<FormsSPW2>();
            this.FormsSZV_6 = new HashSet<FormsSZV_6>();
            this.FormsSZV_6_4 = new HashSet<FormsSZV_6_4>();
            this.FormsSZV_ISH_4_2017 = new HashSet<FormsSZV_ISH_4_2017>();
            this.TariffCodePlatCat = new HashSet<TariffCodePlatCat>();
            this.TariffPlat = new HashSet<TariffPlat>();
            this.FormsSZV_KORR_2017 = new HashSet<FormsSZV_KORR_2017>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public long PlatCategoryRaschPerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsRSW2014_1_Razd_6_4> FormsRSW2014_1_Razd_6_4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSPW2> FormsSPW2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_6> FormsSZV_6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_6_4> FormsSZV_6_4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_ISH_4_2017> FormsSZV_ISH_4_2017 { get; set; }
        public virtual PlatCategoryRaschPer PlatCategoryRaschPer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TariffCodePlatCat> TariffCodePlatCat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TariffPlat> TariffPlat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_KORR_2017> FormsSZV_KORR_2017 { get; set; }
    }
}
