//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecOcenkaUslTrudaDopTariff
    {
        public long ID { get; set; }
        public Nullable<long> SpecOcenkaUslTrudaID { get; set; }
        public Nullable<byte> Type { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<decimal> Rate { get; set; }
    
        public virtual SpecOcenkaUslTruda SpecOcenkaUslTruda { get; set; }
    }
}
