//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecOcenkaUslTruda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecOcenkaUslTruda()
        {
            this.FormsRSW2014_1_Razd_6_7 = new HashSet<FormsRSW2014_1_Razd_6_7>();
            this.FormsSZV_ISH_7_2017 = new HashSet<FormsSZV_ISH_7_2017>();
            this.FormsSZV_KORR_5_2017 = new HashSet<FormsSZV_KORR_5_2017>();
            this.SpecOcenkaUslTrudaDopTariff = new HashSet<SpecOcenkaUslTrudaDopTariff>();
        }
    
        public long ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsRSW2014_1_Razd_6_7> FormsRSW2014_1_Razd_6_7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_ISH_7_2017> FormsSZV_ISH_7_2017 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormsSZV_KORR_5_2017> FormsSZV_KORR_5_2017 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecOcenkaUslTrudaDopTariff> SpecOcenkaUslTrudaDopTariff { get; set; }
    }
}
