//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffList
    {
        public long ID { get; set; }
        public Nullable<long> Num { get; set; }
        public string FIO { get; set; }
        public string InsuranceNum { get; set; }
        public string InfoType { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<long> XmlInfoID { get; set; }
        public Nullable<long> StaffID { get; set; }
        public Nullable<long> FormsRSW_6_1_ID { get; set; }
    
        public virtual xmlInfo xmlInfo { get; set; }
    }
}
