//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffInfo
    {
        public long ID { get; set; }
        public long StaffID { get; set; }
        public string DateBirthType { get; set; }
        public Nullable<byte> DateBirthDay { get; set; }
        public Nullable<byte> DateBirthMonth { get; set; }
        public Nullable<short> DateBirthYear { get; set; }
        public string PlaceBirthType { get; set; }
        public string Punkt { get; set; }
        public string District { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public string Citizenship { get; set; }
        public Nullable<long> DocumentTypesID { get; set; }
        public string DocName { get; set; }
        public string DocSer { get; set; }
        public string DocNum { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocWho { get; set; }
        public string AddressReg { get; set; }
        public string AddressFact { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DateZapoln { get; set; }
        public Nullable<byte> DispatchPFR { get; set; }
    
        public virtual DocumentTypes DocumentTypes { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
