//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StajOsn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StajOsn()
        {
            this.StajLgot = new HashSet<StajLgot>();
        }
    
        public long ID { get; set; }
        public Nullable<long> FormsRSW2014_1_Razd_6_1_ID { get; set; }
        public Nullable<long> FormsSPW2_ID { get; set; }
        public Nullable<long> FormsSZV_6_4_ID { get; set; }
        public Nullable<long> FormsSZV_6_ID { get; set; }
        public Nullable<long> Number { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<long> KodVred_OsnID { get; set; }
        public Nullable<long> KodVred_DopID { get; set; }
        public Nullable<long> TerrUslID { get; set; }
        public Nullable<decimal> TerrUslKoef { get; set; }
        public Nullable<long> OsobUslTrudaID { get; set; }
        public Nullable<long> DolgnID { get; set; }
        public Nullable<long> IschislStrahStajOsnID { get; set; }
        public Nullable<long> IschislStrahStajDopID { get; set; }
        public Nullable<long> Strah1Param { get; set; }
        public Nullable<long> Strah2Param { get; set; }
        public Nullable<long> UslDosrNaznID { get; set; }
        public Nullable<long> UslDosrNazn1Param { get; set; }
        public Nullable<long> UslDosrNazn2Param { get; set; }
        public Nullable<decimal> UslDosrNazn3Param { get; set; }
        public Nullable<long> FormsSZV_STAJ_2017_ID { get; set; }
        public Nullable<long> FormsSZV_ISH_2017_ID { get; set; }
        public Nullable<long> FormsSZV_KORR_2017_ID { get; set; }
        public Nullable<bool> CodeBEZR { get; set; }
    
        public virtual Dolgn Dolgn { get; set; }
        public virtual FormsRSW2014_1_Razd_6_1 FormsRSW2014_1_Razd_6_1 { get; set; }
        public virtual FormsSPW2 FormsSPW2 { get; set; }
        public virtual FormsSZV_6 FormsSZV_6 { get; set; }
        public virtual FormsSZV_6_4 FormsSZV_6_4 { get; set; }
        public virtual FormsSZV_STAJ_2017 FormsSZV_STAJ_2017 { get; set; }
        public virtual IschislStrahStajDop IschislStrahStajDop { get; set; }
        public virtual IschislStrahStajOsn IschislStrahStajOsn { get; set; }
        public virtual KodVred_2 KodVred_2 { get; set; }
        public virtual KodVred_3 KodVred_3 { get; set; }
        public virtual OsobUslTruda OsobUslTruda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StajLgot> StajLgot { get; set; }
        public virtual UslDosrNazn UslDosrNazn { get; set; }
        public virtual TerrUsl TerrUsl { get; set; }
        public virtual FormsSZV_KORR_2017 FormsSZV_KORR_2017 { get; set; }
        public virtual FormsSZV_ISH_2017 FormsSZV_ISH_2017 { get; set; }
    }
}
