//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StajLgot
    {
        public long ID { get; set; }
        public long StajOsnID { get; set; }
        public Nullable<long> Number { get; set; }
        public Nullable<long> KodVred_OsnID { get; set; }
        public Nullable<long> KodVred_DopID { get; set; }
        public Nullable<long> TerrUslID { get; set; }
        public Nullable<long> OsobUslTrudaID { get; set; }
        public Nullable<long> DolgnID { get; set; }
        public Nullable<long> IschislStrahStajOsnID { get; set; }
        public Nullable<long> IschislStrahStajDopID { get; set; }
        public Nullable<long> Strah1Param { get; set; }
        public Nullable<long> Strah2Param { get; set; }
        public Nullable<long> UslDosrNaznID { get; set; }
        public Nullable<long> UslDosrNazn1Param { get; set; }
        public Nullable<long> UslDosrNazn2Param { get; set; }
        public Nullable<decimal> UslDosrNazn3Param { get; set; }
        public Nullable<decimal> TerrUslKoef { get; set; }
    
        public virtual Dolgn Dolgn { get; set; }
        public virtual IschislStrahStajDop IschislStrahStajDop { get; set; }
        public virtual IschislStrahStajOsn IschislStrahStajOsn { get; set; }
        public virtual KodVred_2 KodVred_2 { get; set; }
        public virtual KodVred_3 KodVred_3 { get; set; }
        public virtual OsobUslTruda OsobUslTruda { get; set; }
        public virtual UslDosrNazn UslDosrNazn { get; set; }
        public virtual TerrUsl TerrUsl { get; set; }
        public virtual StajOsn StajOsn { get; set; }
    }
}
