//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffCodePlatCat
    {
        public long ID { get; set; }
        public Nullable<long> PlatCategoryID { get; set; }
        public Nullable<long> TariffCodeID { get; set; }
    
        public virtual PlatCategory PlatCategory { get; set; }
        public virtual TariffCode TariffCode { get; set; }
    }
}
