//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TariffPlat
    {
        public long ID { get; set; }
        public long PlatCategoryID { get; set; }
        public Nullable<short> Year { get; set; }
        public Nullable<decimal> StrahPercant1966 { get; set; }
        public Nullable<decimal> StrahPercent1967 { get; set; }
        public Nullable<decimal> NakopPercant { get; set; }
        public Nullable<decimal> FFOMS_Percent { get; set; }
        public Nullable<decimal> TFOMS_Percent { get; set; }
    
        public virtual PlatCategory PlatCategory { get; set; }
    }
}
