//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersActivity
    {
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Action { get; set; }
        public string Info { get; set; }
        public string TableName { get; set; }
        public Nullable<long> TableID { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
