//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xmlFile
    {
        public long ID { get; set; }
        public string XmlContent { get; set; }
        public Nullable<long> XmlInfoID { get; set; }
    
        public virtual xmlInfo xmlInfo { get; set; }
    }
}
