//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAGS_Death
    {
        public long ID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<byte> Sex { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public Nullable<short> Type_DateBirth { get; set; }
        public Nullable<short> DateBirthDay_Os { get; set; }
        public Nullable<short> DateBirthMonth_Os { get; set; }
        public Nullable<short> DateBirthYear_Os { get; set; }
        public Nullable<short> Type_PlaceBirth { get; set; }
        public string PunktBirth { get; set; }
        public string DistrBirth { get; set; }
        public string RegionBirth { get; set; }
        public string CountryBirth { get; set; }
        public Nullable<System.DateTime> DateDeath { get; set; }
        public Nullable<short> Type_DateDeath { get; set; }
        public Nullable<short> DateDeathDay_Os { get; set; }
        public Nullable<short> DateDeathMonth_Os { get; set; }
        public Nullable<short> DateDeathYear_Os { get; set; }
        public string RegionDeath { get; set; }
        public string RegionDeath_sokr { get; set; }
        public string DistrDeath { get; set; }
        public string DistrDeath_sokr { get; set; }
        public string CityDeath { get; set; }
        public string CityDeath_sokr { get; set; }
        public string PunktDeath { get; set; }
        public string PunktDeath_sokr { get; set; }
        public string StreetDeath { get; set; }
        public string StreetDeath_sokr { get; set; }
        public string DomDeath { get; set; }
        public string DomDeath_sokr { get; set; }
        public string StroenDeath { get; set; }
        public string StroenDeath_sokr { get; set; }
        public string KorpDeath { get; set; }
        public string KorpDeath_sokr { get; set; }
        public string KvartDeath { get; set; }
        public string KvartDeath_sokr { get; set; }
        public string RegionLast { get; set; }
        public string RegionLast_sokr { get; set; }
        public string DistrLast { get; set; }
        public string DistrLast_sokr { get; set; }
        public string CityLast { get; set; }
        public string CityLast_sokr { get; set; }
        public string PunktLast { get; set; }
        public string PunktLast_sokr { get; set; }
        public string StreetLast { get; set; }
        public string StreetLast_sokr { get; set; }
        public string DomLast { get; set; }
        public string DomLast_sokr { get; set; }
        public string StroenLast { get; set; }
        public string StroenLast_sokr { get; set; }
        public string KorpLast { get; set; }
        public string KorpLast_sokr { get; set; }
        public string KvartLast { get; set; }
        public string KvartLast_sokr { get; set; }
        public string Akt_Num { get; set; }
        public Nullable<System.DateTime> Akt_Date { get; set; }
        public string Akt_OrgZags { get; set; }
    }
}
