//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZAGS_Born
    {
        public long ID { get; set; }
        public string cLastName { get; set; }
        public string cFirstName { get; set; }
        public string cMiddleName { get; set; }
        public Nullable<byte> cSex { get; set; }
        public Nullable<System.DateTime> cDateBirth { get; set; }
        public Nullable<short> cType_DateBirth { get; set; }
        public Nullable<short> cDateBirthDay_Os { get; set; }
        public Nullable<short> cDateBirthMonth_Os { get; set; }
        public Nullable<short> cDateBirthYear_Os { get; set; }
        public Nullable<short> cType_PlaceBirth { get; set; }
        public string cPunkt { get; set; }
        public string cDistr { get; set; }
        public string cRegion { get; set; }
        public string cCountry { get; set; }
        public string cAkt_Num { get; set; }
        public Nullable<System.DateTime> cAkt_Date { get; set; }
        public string cAkt_OrgZags { get; set; }
        public string cSvid_Ser { get; set; }
        public string cSvid_Num { get; set; }
        public Nullable<System.DateTime> cSvid_Date { get; set; }
        public string cSvid_OrgZags { get; set; }
        public string mLastName { get; set; }
        public string mFirstName { get; set; }
        public string mMiddleName { get; set; }
        public string mCitizenship { get; set; }
        public Nullable<System.DateTime> mDateBirth { get; set; }
        public Nullable<short> mType_DateBirth { get; set; }
        public Nullable<short> mDateBirthDay_Os { get; set; }
        public Nullable<short> mDateBirthMonth_Os { get; set; }
        public Nullable<short> mDateBirthYear_Os { get; set; }
        public Nullable<short> mType_PlaceBirth { get; set; }
        public string mPunkt { get; set; }
        public string mDistr { get; set; }
        public string mRegion { get; set; }
        public string mCountry { get; set; }
        public string fLastName { get; set; }
        public string fFirstName { get; set; }
        public string fMiddleName { get; set; }
        public string fCitizenship { get; set; }
        public Nullable<System.DateTime> fDateBirth { get; set; }
        public Nullable<short> fType_DateBirth { get; set; }
        public Nullable<short> fDateBirthDay_Os { get; set; }
        public Nullable<short> fDateBirthMonth_Os { get; set; }
        public Nullable<short> fDateBirthYear_Os { get; set; }
        public Nullable<short> fType_PlaceBirth { get; set; }
        public string fPunkt { get; set; }
        public string fDistr { get; set; }
        public string fRegion { get; set; }
        public string fCountry { get; set; }
    }
}
